[package]
name = "gen-polygons"
version = "0.1.0"
authors = ["Markus Hällfors <markus@hallfors.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "^0.25.10"
env_logger = "^0.11.10"
log = "^0.4.32"
wgpu = "^29.0.3"
futures = "^0.3.32"
bytemuck = { version = "^1.25.0", features = [ "derive" ] }
rand = "^0.10.1"
ctrlc = "^3.5.2"
chrono = { version = "^0.4.45", default-features = false, features = ["clock"] }
winit = "^0.30"
rusqlite = { version = "^0.40.1", features = ["bundled"] }
thiserror = "^2.0.18"
ratatui = "^0.30.1"
crossterm = "^0.29.0"
tui-input = "^0.15.3"

[dev-dependencies]
tempfile = "^3.27.0"

[[bin]]
name = "polygenvo"
path = "src/polygenvo/main.rs"